//=======================================================================
// SegmentConeSurfaceCandidates.RimPoints.cs
//=======================================================================
// MIT License, Copyright (c) 2024-present David Oravsky (mrdav30)
// See LICENSE file in the project root for full license information.
//=======================================================================
using System;
using static FixedMathSharp.Geometry.CylinderContactAlgebra;
using static FixedMathSharp.Geometry.ContactQuadratic;

namespace FixedMathSharp.Geometry;

/// <content>Endpoint and axial-edge rim pairs, including exact rotational domains.</content>
internal static partial class SegmentConeSurfaceCandidates
{
    private static void AccumulateRimPoints(in SegmentConeSurfaceGeometry geometry, ref ConeSurfaceSelection selection)
    {
        if (geometry.Radius.IsZero)
            return;
        int first = !geometry.Edge.IsZero && geometry.Edge.Y.IsZero || HasSlantedHorizontalRimFoot(geometry) ? -2
            : geometry.Edge.X.IsZero && geometry.Edge.Z.IsZero && !geometry.Edge.Y.IsZero ? -1 : 0;
        int last = geometry.Edge.IsZero ? 0 : 1;
        Span<ulong> values = stackalloc ulong[10 * Words];
        Span<int> signs = stackalloc int[10];
        Span<ulong> root = stackalloc ulong[Words];
        for (int endpoint = first; endpoint <= last; endpoint++)
        {
            if (endpoint < 0 && endpoint != first)
                continue;
            if (!TryGetRimPoint(geometry, endpoint, out WideAxis3 radialAxis, out Signed576 radialCoefficient,
                    out Signed320 axialOffset, out _, out _))
                continue;
            Signed576 radialSquare = radialAxis.SquaredLength;
            if (radialSquare.IsZero)
            {
                if (HasRimCircleDomain(geometry, axialOffset, endpoint, values, signs, root))
                    selection.Add(new SegmentConeSurfaceCandidate(geometry.Input, ConeSurfaceFeature.Rim,
                        ConeSurfaceFamily.RotationCircle, -2, endpoint, endpoint < 0 ? ConeSurfacePointLocation.Interior
                            : endpoint == 0 ? ConeSurfacePointLocation.Start : ConeSurfacePointLocation.End));
                continue;
            }
            Import(radialSquare, root);
            for (int branch = -1; branch <= 1; branch += 2)
            {
                BuildRimPointNormal(geometry, radialAxis, radialCoefficient, axialOffset, radialSquare, branch, values, signs);
                if (!AdmitsEndpointNormal(geometry.Edge, endpoint, values, signs, root))
                    continue;
                bool zero = At(values, signs, 0).Sign(root) == 0 && At(values, signs, 1).Sign(root) == 0 && At(values, signs, 2).Sign(root) == 0;
                if (zero && !HasRimTouchDomain(geometry, radialAxis, branch, endpoint))
                    continue;
                selection.Add(new SegmentConeSurfaceCandidate(geometry.Input, ConeSurfaceFeature.Rim,
                    zero ? ConeSurfaceFamily.NormalCone : ConeSurfaceFamily.None,
                    branch > 0 ? -2 : -3, endpoint, endpoint < 0 ? ConeSurfacePointLocation.Interior
                        : endpoint == 0 ? ConeSurfacePointLocation.Start : ConeSurfacePointLocation.End));
            }
        }
    }

    private static bool HasSlantedHorizontalRimFoot(in SegmentConeSurfaceGeometry geometry)
    {
        if (geometry.Edge.Y.IsZero || IsMeridionalRim(geometry)
            || geometry.Edge.X.IsZero && geometry.Edge.Z.IsZero)
            return false;
        // At a horizontal stationary normal both unsquared chart factors
        // vanish. The radial affine foot must lie exactly in the base plane:
        // C_y|E_rad|²-(C_rad.E_rad)E_y=0. Products are <596 bits.
        return WideArithmetic.SubtractSigned832(
            WideArithmetic.MultiplySigned576ToSigned832(CircularRimContactAlgebra.RadialDot(geometry.Edge, geometry.Edge), geometry.BaseOffset.Y),
            WideArithmetic.MultiplySigned576ToSigned832(CircularRimContactAlgebra.RadialDot(geometry.BaseOffset, geometry.Edge), geometry.Edge.Y)).IsZero;
    }

    private static bool HasRimTouchDomain(in SegmentConeSurfaceGeometry geometry, WideAxis3 radialAxis, int branch, int endpoint)
    {
        // The rim normal cone is generated by inward side and upward base
        // normals. A nonzero nonnegative combination satisfies the segment
        // tangent condition exactly when their scalar projections straddle
        // zero (interior), or one generator has the endpoint's required sign.
        Span<ulong> values = stackalloc ulong[2 * Words];
        Span<int> signs = stackalloc int[2];
        Span<ulong> root = stackalloc ulong[Words];
        ContactQuadratic side = At(values, signs, 0);
        side.Set(WideArithmetic.MultiplySigned576(CircularRimContactAlgebra.RadialDot(radialAxis, geometry.Edge), geometry.Input.Height.m_rawValue));
        side.MultiplySign(-branch);
        Signed576 vertical = WideArithmetic.MultiplySigned320(geometry.Edge.Y, Signed192.Raw(geometry.Input.Radius));
        Import(vertical, side.Radical); side.Signs[1] = -vertical.Sign;
        Import(radialAxis.SquaredLength, root);
        int sideSign = side.Sign(root), baseSign = geometry.Edge.Y.Sign;
        return endpoint < 0 ? sideSign == 0 || sideSign != baseSign
            : endpoint == 0 ? sideSign <= 0 || baseSign <= 0 : sideSign >= 0 || baseSign >= 0;
    }

    private static bool TryGetRimPoint(in SegmentConeSurfaceGeometry geometry, int endpoint,
        out WideAxis3 radialAxis, out Signed576 radialCoefficient, out Signed320 axialOffset,
        out Signed576 numerator, out Signed576 denominator)
    {
        denominator = Signed576.ExtendValue(Signed320.ExtendValue(Signed192.Signed(1)));
        numerator = endpoint == 1 ? denominator : default;
        WideAxis3 point = endpoint == 1 ? geometry.B : geometry.A;
        radialAxis = new WideAxis3(point.X, default, point.Z);
        radialCoefficient = radialAxis.SquaredLength;
        axialOffset = WideArithmetic.AddSigned320(point.Y, geometry.Finite.ShapeFrame.Cap);
        if (endpoint >= 0)
            return geometry.Finite.ContainsTransformedPoint(geometry.Finite.Transform(endpoint == 0
                ? geometry.Input.Segment.Start : geometry.Input.Segment.End));
        if (endpoint == -2)
        {
            radialAxis = new WideAxis3(WideArithmetic.Negate(geometry.Edge.Z), default, geometry.Edge.X);
            denominator = radialAxis.SquaredLength;
            numerator = WideArithmetic.SubtractSigned576(default, CircularRimContactAlgebra.RadialDot(geometry.A, geometry.Edge));
            radialCoefficient = WideAxis3.Dot(geometry.A, radialAxis);
            if (numerator.Sign <= 0 || WideArithmetic.SubtractSigned576(denominator, numerator).Sign <= 0)
                return false;
            Signed320 pointY = geometry.A.Y;
            if (!geometry.Edge.Y.IsZero)
            {
                // HasSlantedHorizontalRimFoot established this exact height.
                pointY = WideArithmetic.Negate(geometry.Finite.ShapeFrame.Cap);
                axialOffset = default;
            }
            return ContainsCenteredRatio(geometry,
                WideArithmetic.MultiplySigned576ToSigned832(radialCoefficient, radialAxis.X),
                WideArithmetic.MultiplySigned576ToSigned832(denominator, pointY),
                WideArithmetic.MultiplySigned576ToSigned832(radialCoefficient, radialAxis.Z), denominator);
        }
        numerator = WideArithmetic.SubtractSigned576(default, Signed576.ExtendValue(geometry.BaseOffset.Y));
        denominator = Signed576.ExtendValue(geometry.Edge.Y);
        if (denominator.Sign < 0)
        {
            denominator = WideArithmetic.SubtractSigned576(default, denominator);
            numerator = WideArithmetic.SubtractSigned576(default, numerator);
        }
        if (numerator.Sign <= 0 || WideArithmetic.SubtractSigned576(denominator, numerator).Sign <= 0)
            return false;
        axialOffset = default;
        return WideArithmetic.SubtractSigned576(radialCoefficient,
            WideArithmetic.MultiplySigned320(geometry.Radius, geometry.Radius)).Sign <= 0;
    }

    private static void BuildRimPointNormal(in SegmentConeSurfaceGeometry geometry, WideAxis3 radialAxis,
        Signed576 radialCoefficient, Signed320 axialOffset, Signed576 radialSquare, int branch, Span<ulong> values, Span<int> signs)
    {
        ContactQuadratic component = At(values, signs, 3);
        for (int axis = 0; axis < 3; axis++)
        {
            Signed320 coordinate = axis == 1 ? axialOffset : Component(radialAxis, axis);
            component.Set(Signed576.ExtendValue(coordinate));
            ContactQuadratic normal = At(values, signs, axis);
            Scale(component, axis == 1 ? radialSquare : radialCoefficient, normal);
            if (axis == 1) continue;
            Signed576 radical = WideArithmetic.MultiplySigned320(geometry.Radius, coordinate);
            Import(radical, normal.Radical); normal.Signs[1] = -branch * radical.Sign;
        }
    }

    private static bool AdmitsEndpointNormal(WideAxis3 edge, int endpoint,
        Span<ulong> values, Span<int> signs, ReadOnlySpan<ulong> root)
    {
        ContactQuadratic sum = At(values, signs, 3), product = At(values, signs, 4);
        sum.Clear();
        for (int axis = 0; axis < 3; axis++)
        {
            Scale(At(values, signs, axis), Signed576.ExtendValue(Component(edge, axis)), product);
            sum.Add(product);
        }
        int sign = sum.Sign(root);
        return endpoint < 0 ? sign == 0 : endpoint == 0 ? sign <= 0 : sign >= 0;
    }

    private static bool HasRimCircleDomain(in SegmentConeSurfaceGeometry geometry, Signed320 axialOffset, int endpoint,
        Span<ulong> values, Span<int> signs, Span<ulong> root)
    {
        if (endpoint < 0)
            return true;
        ContactQuadratic bound = At(values, signs, 0);
        bound.Set(WideArithmetic.MultiplySigned320(axialOffset, geometry.Edge.Y));
        Import(geometry.Radius, bound.Radical); bound.Signs[1] = endpoint == 0 ? -1 : 1;
        Import(CircularRimContactAlgebra.RadialDot(geometry.Edge, geometry.Edge), root);
        int sign = bound.Sign(root);
        return endpoint == 0 ? sign <= 0 : sign >= 0;
    }

    internal static FixedContactAnchors GetRimPointContact(SegmentConeSurfaceCandidate candidate)
    {
        if (candidate.RootOrdinal <= -3)
            return GetMeridionalRimContact(candidate);
        var geometry = new SegmentConeSurfaceGeometry(candidate.Input);
        bool admitted = TryGetRimPoint(geometry, candidate.RootOrdinal, out WideAxis3 radialAxis,
            out Signed576 radialCoefficient, out Signed320 axialOffset, out Signed576 numerator, out Signed576 denominator);
        System.Diagnostics.Debug.Assert(admitted);
        Span<ulong> values = stackalloc ulong[10 * Words];
        Span<int> signs = stackalloc int[10];
        Span<ulong> root = stackalloc ulong[Words];
        Signed576 radialSquare = radialAxis.SquaredLength;
        Import(radialSquare, root);
        int branch = candidate.Chart == -2 ? 1 : -1;
        BuildRimPointNormal(geometry, radialAxis, radialCoefficient, axialOffset, radialSquare, branch, values, signs);
        Vector3d radial = MaterializeRadialDirection(radialAxis, candidate.Input.Radius, branch);
        return MaterializeRimPoint(geometry, numerator, denominator, values, signs, root, radial, false);
    }

    internal static bool TryGetRimCircleContact(SegmentConeSurfaceCandidate candidate, Vector2d direction, out FixedContactAnchors contact)
    {
        contact = default;
        if (candidate.Feature != ConeSurfaceFeature.Rim || candidate.Family != ConeSurfaceFamily.RotationCircle || direction == Vector2d.Zero)
            return false;
        var geometry = new SegmentConeSurfaceGeometry(candidate.Input);
        bool admitted = TryGetRimPoint(geometry, candidate.RootOrdinal, out _, out _, out Signed320 axialOffset,
            out Signed576 numerator, out Signed576 denominator);
        System.Diagnostics.Debug.Assert(admitted);
        WideAxis3 radialDirection = new(Signed320.ExtendValue(Signed192.Raw(direction.X)), default, Signed320.ExtendValue(Signed192.Raw(direction.Y)));
        Span<ulong> values = stackalloc ulong[10 * Words];
        Span<int> signs = stackalloc int[10];
        Span<ulong> root = stackalloc ulong[Words];
        BuildRimCircleNormal(geometry, radialDirection, axialOffset, values, signs, root);
        if (!AdmitsEndpointNormal(geometry.Edge, candidate.RootOrdinal, values, signs, root))
            return false;
        Vector3d radial = MaterializeRadialDirection(radialDirection, candidate.Input.Radius, 1);
        contact = MaterializeRimPoint(geometry, numerator, denominator, values, signs, root, radial, true);
        return true;
    }

    private static void BuildRimCircleNormal(in SegmentConeSurfaceGeometry geometry, WideAxis3 radialDirection,
        Signed320 axialOffset, Span<ulong> values, Span<int> signs, Span<ulong> root)
    {
        Import(radialDirection.SquaredLength, root);
        At(values, signs, 0).Set(WideArithmetic.SubtractSigned576(default, WideArithmetic.MultiplySigned320(geometry.Radius, radialDirection.X)));
        At(values, signs, 2).Set(WideArithmetic.SubtractSigned576(default, WideArithmetic.MultiplySigned320(geometry.Radius, radialDirection.Z)));
        ContactQuadratic axial = At(values, signs, 1);
        axial.Clear();
        Import(axialOffset, axial.Radical); axial.Signs[1] = axialOffset.Sign;
    }

    private static bool TryGetRimTouchContact(SegmentConeSurfaceCandidate candidate, Signed576 nx, Signed576 ny, Signed576 nz,
        out FixedContactAnchors contact)
    {
        contact = default;
        System.Diagnostics.Debug.Assert(candidate.Feature == ConeSurfaceFeature.Rim);
        if (candidate.Family != ConeSurfaceFamily.NormalCone || nx.IsZero && ny.IsZero && nz.IsZero)
            return false;
        if (candidate.RootOrdinal <= -3)
            return TryGetMeridionalRimTouchContact(candidate, nx, ny, nz, out contact);
        var geometry = new SegmentConeSurfaceGeometry(candidate.Input);
        bool admitted = TryGetRimPoint(geometry, candidate.RootOrdinal, out WideAxis3 radialAxis, out _, out _,
            out Signed576 numerator, out Signed576 denominator);
        System.Diagnostics.Debug.Assert(admitted);
        int branch = candidate.Chart == -2 ? 1 : -1;
        if (!AdmitsRimTouchNormal(geometry, radialAxis, branch, candidate.RootOrdinal, nx, ny, nz, out Vector3d normal))
            return false;
        Vector3d point = new(RoundSegmentCoordinate(candidate.Input.Segment.Start.X, candidate.Input.Segment.End.X, numerator, denominator),
            RoundSegmentCoordinate(candidate.Input.Segment.Start.Y, candidate.Input.Segment.End.Y, numerator, denominator),
            RoundSegmentCoordinate(candidate.Input.Segment.Start.Z, candidate.Input.Segment.End.Z, numerator, denominator));
        contact = new FixedContactAnchors(new FixedPointAnchor(candidate.Input.Origin, candidate.Input.Rotation, point),
            TriangleCircularGeometry.GetSupport(candidate.Input.Center, candidate.Input.ConeRotation, Signed192.Raw(candidate.Input.Height),
                MaterializeRadialDirection(radialAxis, candidate.Input.Radius, branch), 1), normal, Fixed64.Zero, false);
        return true;
    }

    private static bool AdmitsRimTouchNormal(in SegmentConeSurfaceGeometry geometry, WideAxis3 radialAxis,
        int branch, int endpoint, Signed576 nx, Signed576 ny, Signed576 nz, out Vector3d normal)
    {
        normal = default;
        if (!WideArithmetic.SubtractSigned832(WideArithmetic.MultiplySigned576ToSigned832(nx, radialAxis.Z),
                WideArithmetic.MultiplySigned576ToSigned832(nz, radialAxis.X)).IsZero)
            return false;
        if (branch * NormalEdgeDot(nx, default, nz, radialAxis) > 0)
            return false;
        Signed832 x = Signed832.ExtendValue(nx), y = Signed832.ExtendValue(ny), z = Signed832.ExtendValue(nz);
        if (ny.Sign < 0 && CompareWeightedSquares(x, z, geometry.Input.Radius, y, geometry.Input.Height) < 0)
            return false;
        int tangent = NormalEdgeDot(nx, ny, nz, geometry.Edge);
        if (endpoint < 0 ? tangent != 0 : endpoint == 0 ? tangent > 0 : tangent < 0)
            return false;
        normal = MaterializeRationalNormal(x, y, z, geometry.Input.ConeRotation);
        return true;
    }

    private static FixedContactAnchors MaterializeRimPoint(in SegmentConeSurfaceGeometry geometry,
        Signed576 numerator, Signed576 denominator, Span<ulong> normals, Span<int> normalSigns,
        ReadOnlySpan<ulong> root, Vector3d radial, bool circle)
    {
        Vector3d normal = MaterializeQuadraticNormal(normals, normalSigns, root, geometry.Input.ConeRotation);
        Span<ulong> values = stackalloc ulong[6 * Words];
        Span<int> signs = stackalloc int[6];
        ContactQuadratic square = At(values, signs, 0), sum = At(values, signs, 1), divisor = At(values, signs, 2);
        sum.Clear();
        for (int axis = 0; axis < 3; axis++)
        {
            Multiply(At(normals, normalSigns, axis), At(normals, normalSigns, axis), root, square);
            sum.Add(square);
        }
        divisor.Clear();
        if (circle) root.CopyTo(divisor.Rational);
        else WideArithmetic.MultiplyMagnitudes(root, root, divisor.Rational);
        divisor.Signs[0] = 1;
        Span<ulong> scale = stackalloc ulong[Words], squaredScale = stackalloc ulong[Words];
        Import(Signed320.ExtendValue(geometry.RawScale), scale);
        WideArithmetic.MultiplyMagnitudes(scale, scale, squaredScale);
        Scale(divisor, squaredScale, 1, square);
        bool represented = TryRoundSquareRootRatio(sum, square, root, out Fixed64 depth);
        Vector3d point = new(RoundSegmentCoordinate(geometry.Input.Segment.Start.X, geometry.Input.Segment.End.X, numerator, denominator),
            RoundSegmentCoordinate(geometry.Input.Segment.Start.Y, geometry.Input.Segment.End.Y, numerator, denominator),
            RoundSegmentCoordinate(geometry.Input.Segment.Start.Z, geometry.Input.Segment.End.Z, numerator, denominator));
        return new FixedContactAnchors(new FixedPointAnchor(geometry.Input.Origin, geometry.Input.Rotation, point),
            TriangleCircularGeometry.GetSupport(geometry.Input.Center, geometry.Input.ConeRotation, Signed192.Raw(geometry.Input.Height), radial, 1),
            normal, represented ? depth : Fixed64.MaxValue, !represented);
    }

    private static Vector3d MaterializeRadialDirection(WideAxis3 direction, Fixed64 radius, int orientation)
    {
        Span<ulong> values = stackalloc ulong[7 * Words];
        Span<int> signs = stackalloc int[7];
        values.Clear(); signs.Clear();
        for (int axis = 0; axis < 3; axis++)
        {
            Signed320 coordinate = Component(direction, axis);
            Import(coordinate, Slot(values, axis)); signs[axis] = orientation * coordinate.Sign;
        }
        return WideConvexPrismRelations.GetConvexContactCandidateScaledNormal(new ConvexContactCandidate(values, signs, 0), radius);
    }

    private static Vector3d MaterializeQuadraticNormal(Span<ulong> normals, Span<int> normalSigns,
        ReadOnlySpan<ulong> root, FixedQuaternion rotation)
    {
        // Meridional coefficients <996 bits and root <1595; rotating adds
        // <65 bits. Complete metric coefficients remain below 2130 bits.
        Span<ulong> local = stackalloc ulong[7 * Words], world = stackalloc ulong[7 * Words];
        Span<int> localSigns = stackalloc int[7], worldSigns = stackalloc int[7];
        local.Clear(); world.Clear(); localSigns.Clear(); worldSigns.Clear();
        for (int axis = 0; axis < 3; axis++)
        {
            ContactQuadratic n = At(normals, normalSigns, axis);
            n.Rational.CopyTo(Slot(local, axis)); n.Radical.CopyTo(Slot(local, axis + 3));
            localSigns[axis] = n.Signs[0]; localSigns[axis + 3] = n.Signs[1];
        }
        root.CopyTo(Slot(world, 6));
        var basis = new WideRationalBasis3d(rotation);
        WriteWorldDirection(basis, local[..(3 * Words)], localSigns[..3], world[..(3 * Words)], worldSigns[..3]);
        WriteWorldDirection(basis, local.Slice(3 * Words, 3 * Words), localSigns.Slice(3, 3), world.Slice(3 * Words, 3 * Words), worldSigns.Slice(3, 3));
        return WideConvexPrismRelations.GetConvexContactCandidateNormal(new ConvexContactCandidate(world, worldSigns, 0));
    }
}
