name: .NET CI

on:
  push:
    branches-ignore:
      - 'dependabot/**'
      - 'gh-pages'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.1
      with:
        versionSpec: '6.0.x'

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.sln') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Determine Version
      shell: bash
      run: |
        dotnet-gitversion /output json > version.json
        FULL_SEM_VER=$(jq -r .FullSemVer version.json)
        ASSEMBLY_VERSION=$(jq -r .AssemblySemFileVer version.json)
        echo "FULL_SEM_VER=$FULL_SEM_VER" >> $GITHUB_ENV
        echo "ASSEMBLY_VERSION=$ASSEMBLY_VERSION" >> $GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Solution
      run: |
        echo "Version: ${{ env.FULL_SEM_VER }}"
        echo "Assembly Version: ${{ env.ASSEMBLY_VERSION }}"
        dotnet build --configuration Debug --no-restore

    - name: Run Tests (net8.0)
      run: dotnet test --configuration Debug --no-build --verbosity normal